### ISSUE TITLE
Swift module compile error

### ISSUE THREAD

**Issue by sethsamuel** [magnetsystems/message-ios#25]
I'm trying to use the MMX pod in a Swift project, but I'm getting a string of `Include of non-modular header inside framework module` errors.

**Comment by priteshshah1983** [comment]
I was not able to reproduce the issue. I created a new project here: https://github.com/priteshshah1983/SwiftMessage.git and imported ````MMX```` using Cocoapods. By the way, I'm running the latest version of Cocoapods.

````bash
$ pod --version
0.38.2
````

More details would help.

**Comment by sethsamuel** [comment]
The problem occurs when you have `use_frameworks!` in your Podfile, which is necessary for using Swift pods.

**Comment by priteshshah1983** [comment]
@sethsamuel I was able to put in a quick fix in my sample skeleton project here: https://github.com/priteshshah1983/SwiftMessage/commit/2a8644aab823e6d4964f47a8153fba69a790339f

We will figure out the best way to put these changes into the official repo.

The key fixes are some imports and this one:
https://github.com/priteshshah1983/SwiftMessage/blob/2a8644aab823e6d4964f47a8153fba69a790339f/modules/module.modulemap

I hope that helps!

**Comment by sethsamuel** [comment]
Thanks Pritesh, looking forward to seeing the updates in the cocoapod!

**Comment by priteshshah1983** [comment]
Trying to find a workaround for what looks like a ````CocoaPods```` bug: https://github.com/CocoaPods/CocoaPods/issues/4094

**Comment by jasonfergz** [comment]
Hi @sethsamuel  I have pushed a new update to the pod. If you update to version 1.5.8 it should resolve your issue. Please let me know if anything else comes up!
