### ISSUE TITLE
Cannot load Configurations.plist with use_frameworks! Podfile

### ISSUE THREAD

**Issue by sethsamuel** [magnetsystems/message-ios#27]
When using `use_frameworks!` each pod is packaged into its own framework with a separate class bundle. This causes `[[NSBundle bundleForClass:[self class]] pathForResource:@"Configurations" ofType:@"plist"]` to fail to find the file.

There should either be a way to specify a configuration file (added bonus of being able to rename the file to increase clarity) or it should fallover to `[NSBundle mainBundle]` if the file isn't found in the class bundle.

**Comment by priteshshah1983** [comment]
````[[NSBundle bundleForClass:[self class]]```` will be useful for test targets. But, we can certainly check ````[NSBundle mainBundle]```` as you suggested. We can fix that easily or you can send a PR :)

**Comment by sethsamuel** [comment]
Created PR #28 to try to fix the problem. It looks like the message-ios Podfile uses a private repo, so did this blind. Hopefully it works :)

**Comment by jasonfergz** [comment]
Hey Seth,

Merged your PR. It will stay as version 1.5.8 so you may need to clear your cache to verify that everything works with your pod.

pod cache clean --all

Let me know if you have any other issues. Have a great weekend!

Jason
