### ISSUE TITLE
Xcode 7.1 - Include of non-modular header inside framework module 'MMXXMPPFramework.DDXMLNode'

### ISSUE THREAD

**Issue by levantAJ** [magnetsystems/message-ios#37]
I have updated Xcode to 7.1 and it throw some errors like this:
<img width="422" alt="screen shot 2015-10-30 at 10 33 34 am" src="https://cloud.githubusercontent.com/assets/6329656/10837917/c6bd952a-7ef1-11e5-9c35-14ef34bd2c7e.png">

```Include of non-modular header inside framework module 'MMXXMPPFramework.XMPPSRVResolver'```

```Include of non-modular header inside framework module 'MMXXMPPFramework.NSString_DDXML'```

Do you have any solution for my case?

**Comment by jasonfergz** [comment]
Is your project an Obj-c project or swift?

**Comment by priteshshah1983** [comment]
Not sure, if this was an issue with `1.x`, but this is not an issue with `2.0`.

Use this `Podfile`:

```ruby
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/magnetsystems/Specs'

platform :ios, '8.0'

use_frameworks!

pod 'MagnetMax', '~> 2.0' 
```
