### ISSUE TITLE
Channel owner online for a channel

### ISSUE THREAD

**Issue by matanvr** [magnetsystems/message-ios#82]
Note: this is not really an issue. 
I am looking on maintaining on whether a channel's owner is online at a given time. 

Currently, I am using the channel last activity timestamp. It is fairly accurate as long as I have a timer thread sending a heartbeat message every couple of seconds. However, I was wondering if there's any cleaner solution for this use case.

**Comment by priteshshah1983** [comment]
Currently, we don't support **presence**. Your approach sounds reasonable for now.

**Comment by matanvr** [comment]
Thanks Pritesh!
